spring.application.name=bca+
# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=uatples
spring.datasource.username=postgres
spring.datasource.password=Panu11111*
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server Configuration
server.port=8080

# JWT Configuration
bca.jwt.secret=9a614237456b46406b4d3647586b6a654d38526367303030
bca.jwt.expiration-ms=900000
